/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traductor;

import java.awt.Color;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author ADMN
 */
public class AdiPal extends javax.swing.JFrame {

    public ArrayList<JLabel> l = new ArrayList();
    public ArrayList<String> s = new ArrayList();
    public String v2[] = new String[10];

    /**
     * Creates new form AdiPal
     */
    public AdiPal() {
        initComponents();
        setSize(875, 570);
        setLocationRelativeTo(null);
        setResizable(false);
        cargar();
        Login.Music.Play("Archivos/mega.mp3");
    }

    public void cargar() {
        l.add(jLabel2);
        l.add(jLabel3);
        l.add(jLabel4);
        l.add(jLabel5);
        l.add(jLabel6);
        l.add(jLabel7);
        l.add(jLabel8);
        l.add(jLabel9);
        l.add(jLabel10);

        ArrayList<String> pal = new ArrayList();
        for (Palabras aux : Aprender.regist.traer_Palabra()) {
            if (aux.getNivel() == Ejercicios.niv || aux.getNivel() == (Ejercicios.niv - 1)) {
                pal.add(aux.getEnglish());
            }
        }
//      
        int v[] = new int[10];
        int cv = 0;
        System.out.println("Tamaño arreglo: " + pal.size());
        while (cv < 10) {
            boolean val = true;
            int ran = (int) (Math.random() * ((pal.size() - 1) - 0 + 1) + 0);
            for (int i = 0; i < 10; i++) {
                if (ran == v[i]) {
                    val = false;
                }
            }
            if (val == true) {
                v[cv] = ran;
                v2[cv] = pal.get(ran);
                cv++;
            }

        }

        for (int i = 0; i < 9; i++) {
            ImageIcon icon = new ImageIcon(getClass().getResource("Archivos/" + v2[i] + ".jpg"));
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(l.get(i).getWidth(), l.get(i).getHeight(), Image.SCALE_DEFAULT));
            l.get(i).setIcon(icono);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnSh = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Guess The Word");
        getContentPane().setLayout(null);

        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 120, 90);

        jTextField1.setBackground(new java.awt.Color(102, 153, 255));
        jTextField1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 110, 140, 30);

        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 220, 120, 90);

        jTextField2.setBackground(new java.awt.Color(102, 153, 255));
        jTextField2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(150, 250, 140, 30);

        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 360, 120, 90);

        jTextField3.setBackground(new java.awt.Color(102, 153, 255));
        jTextField3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(150, 390, 140, 30);

        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 360, 120, 90);

        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 220, 120, 90);

        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 80, 120, 90);

        jTextField4.setBackground(new java.awt.Color(102, 153, 255));
        jTextField4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(430, 110, 140, 30);

        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel8);
        jLabel8.setBounds(580, 80, 120, 90);

        jTextField7.setBackground(new java.awt.Color(102, 153, 255));
        jTextField7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(710, 110, 140, 30);

        jTextField8.setBackground(new java.awt.Color(102, 153, 255));
        jTextField8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(710, 250, 140, 30);

        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(580, 220, 120, 90);

        jTextField5.setBackground(new java.awt.Color(102, 153, 255));
        jTextField5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(430, 250, 140, 30);

        jTextField6.setBackground(new java.awt.Color(102, 153, 255));
        jTextField6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(430, 390, 140, 30);

        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(580, 360, 120, 90);

        jTextField9.setBackground(new java.awt.Color(102, 153, 255));
        jTextField9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(710, 390, 140, 30);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CHECK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 490, 120, 37);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Guess The Word");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 0, 270, 40);

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Return");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 490, 110, 37);

        btnSh.setBackground(new java.awt.Color(102, 102, 255));
        btnSh.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnSh.setForeground(new java.awt.Color(255, 255, 255));
        btnSh.setText("Show Answers");
        btnSh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShActionPerformed(evt);
            }
        });
        getContentPane().add(btnSh);
        btnSh.setBounds(70, 490, 180, 37);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traductor/222.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 870, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<JTextField> ca = new ArrayList();
        ca.add(jTextField1);
        ca.add(jTextField2);
        ca.add(jTextField3);
        ca.add(jTextField4);
        ca.add(jTextField5);
        ca.add(jTextField6);
        ca.add(jTextField7);
        ca.add(jTextField8);
        ca.add(jTextField9);
        int cont = 0;
        for (int j = 0; j < 9; j++) {
            String caja = ca.get(j).getText();
            if (v2[j].compareTo(caja) == 0) {
                ca.get(j).setBackground(Color.green);
                cont++;
            } else {
                ca.get(j).setBackground(Color.red);
            }
        }
        System.out.println("Contador = " + cont);

        if (cont == 9) {
            Login.nivJug = Login.nivJug + 7;
            Inicio.lNivel.setText("Level " + Login.nivJug);
            Ejercicios.mar++;
            JOptionPane.showMessageDialog(null, "You Win!!!");
            Ejercicios a = new Ejercicios();
            a.setVisible(true);
            if (Ejercicios.mar == 3) {
                Marcianito m = new Marcianito();
                m.setVisible(true);
                Ejercicios.mar = 0;
            }
            this.setVisible(false);
        } else {
            Login.nivJug = Login.nivJug - 1;
            Inicio.lNivel.setText("Level " + Login.nivJug);
            JOptionPane.showMessageDialog(null, "Your level decreased...");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "Do you want to go out?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            Login.nivJug = Login.nivJug - 1;
            Inicio.lNivel.setText("Level " + Login.nivJug);
            Ejercicios.mar = 0;
            Ejercicios abrir = new Ejercicios();
            abrir.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnShActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShActionPerformed
        // TODO add your handling code here:
        ArrayList<JTextField> ca = new ArrayList();
        ca.add(jTextField1);
        ca.add(jTextField2);
        ca.add(jTextField3);
        ca.add(jTextField4);
        ca.add(jTextField5);
        ca.add(jTextField6);
        ca.add(jTextField7);
        ca.add(jTextField8);
        ca.add(jTextField9);
        for (int j = 0; j < 9; j++) {
            ca.get(j).setText(v2[j]);
            ca.get(j).setBackground(Color.DARK_GRAY);
        }
        Login.nivJug = Login.nivJug - 1;
        Inicio.lNivel.setText("Level " + Login.nivJug);
        JOptionPane.showMessageDialog(null, "You Lose...");
        Ejercicios.mar = 0;
        Ejercicios a = new Ejercicios();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnShActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdiPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdiPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdiPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdiPal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdiPal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
