/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traductor;

import java.util.ArrayList;

/**
 *
 * @author ADMN
 */
public class Aprender extends javax.swing.JFrame {
    public static ConsultasBD regist = new ConsultasBD();
    /**
     * Creates new form Aprender
     */
    public Aprender() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(685, 490);
        setResizable(false);
       Login.Music.Stop();
    }

    
    
    public ArrayList<Palabras> colores(){
        ArrayList<Palabras> col = new ArrayList();
        for(Palabras aux: regist.traer_Palabra()){
            if(aux.getTipo().compareTo("color") == 0){
                col.add(aux);
            }
        }
        return col;
    }
    
    public void aumentar(){
        if(Login.nivJug < 10){
            Login.nivJug = Login.nivJug + 2;
            Inicio.lNivel.setText("Level " + Login.nivJug);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnColor = new javax.swing.JButton();
        btnAnima = new javax.swing.JButton();
        btnFrut = new javax.swing.JButton();
        btnFlor = new javax.swing.JButton();
        btnFami = new javax.swing.JButton();
        btnCasa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Learn");
        setMinimumSize(new java.awt.Dimension(620, 480));
        setPreferredSize(new java.awt.Dimension(750, 491));
        getContentPane().setLayout(null);

        btnRegre.setBackground(new java.awt.Color(116, 59, 18));
        btnRegre.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnRegre.setForeground(new java.awt.Color(255, 255, 255));
        btnRegre.setText("Return");
        btnRegre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegreActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegre);
        btnRegre.setBounds(560, 410, 110, 40);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(182, 101, 43));
        jLabel1.setText("LEARN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 10, 170, 40);

        btnColor.setBackground(new java.awt.Color(102, 255, 102));
        btnColor.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnColor.setForeground(new java.awt.Color(0, 0, 0));
        btnColor.setText("COLORS");
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });
        getContentPane().add(btnColor);
        btnColor.setBounds(160, 90, 150, 40);

        btnAnima.setBackground(new java.awt.Color(102, 255, 102));
        btnAnima.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnAnima.setForeground(new java.awt.Color(0, 0, 0));
        btnAnima.setText("ANIMALS");
        btnAnima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnima);
        btnAnima.setBounds(410, 90, 150, 40);

        btnFrut.setBackground(new java.awt.Color(102, 255, 102));
        btnFrut.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnFrut.setForeground(new java.awt.Color(0, 0, 0));
        btnFrut.setText("FRUITS");
        btnFrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrutActionPerformed(evt);
            }
        });
        getContentPane().add(btnFrut);
        btnFrut.setBounds(160, 200, 150, 40);

        btnFlor.setBackground(new java.awt.Color(102, 255, 102));
        btnFlor.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnFlor.setForeground(new java.awt.Color(0, 0, 0));
        btnFlor.setText("FLOWERS");
        btnFlor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlorActionPerformed(evt);
            }
        });
        getContentPane().add(btnFlor);
        btnFlor.setBounds(410, 200, 150, 40);

        btnFami.setBackground(new java.awt.Color(102, 255, 102));
        btnFami.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnFami.setForeground(new java.awt.Color(0, 0, 0));
        btnFami.setText("FAMILY");
        btnFami.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFamiActionPerformed(evt);
            }
        });
        getContentPane().add(btnFami);
        btnFami.setBounds(160, 290, 150, 40);

        btnCasa.setBackground(new java.awt.Color(102, 255, 102));
        btnCasa.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnCasa.setForeground(new java.awt.Color(0, 0, 0));
        btnCasa.setText("HOUSE");
        btnCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCasa);
        btnCasa.setBounds(410, 290, 150, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traductor/anim.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 690, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegreActionPerformed
        // TODO add your handling code here:
//        Inicio abrir = new Inicio();
//        abrir.setVisible(true);
        this.setVisible(false);
        Login.registros.modificarNivel(Login.jugador.getUsuario(), Login.nivJug);
        Login.Music.Stop();
        Login.Music.Play("Archivos/pok.mp3");
    }//GEN-LAST:event_btnRegreActionPerformed

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        // TODO add your handling code here:
        FColor abrir = new FColor();
        abrir.setVisible(true);
        aumentar();
    }//GEN-LAST:event_btnColorActionPerformed

    private void btnAnimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimaActionPerformed
        // TODO add your handling code here:
        FAnimal abrir = new FAnimal();
        abrir.setVisible(true);
        aumentar();
    }//GEN-LAST:event_btnAnimaActionPerformed

    private void btnFrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrutActionPerformed
        // TODO add your handling code here:
        FFruta abrir = new FFruta();
        abrir.setVisible(true);
        aumentar();
    }//GEN-LAST:event_btnFrutActionPerformed

    private void btnFlorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlorActionPerformed
        // TODO add your handling code here:
        FFlor abrir = new FFlor();
        abrir.setVisible(true);
        aumentar();
    }//GEN-LAST:event_btnFlorActionPerformed

    private void btnFamiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFamiActionPerformed
        // TODO add your handling code here:
        FFamilia abrir = new FFamilia();
        abrir.setVisible(true);
        aumentar();
    }//GEN-LAST:event_btnFamiActionPerformed

    private void btnCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasaActionPerformed
        // TODO add your handling code here:
        FCasa abrir = new FCasa();
        abrir.setVisible(true);
        aumentar();
    }//GEN-LAST:event_btnCasaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aprender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aprender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aprender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aprender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aprender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnima;
    private javax.swing.JButton btnCasa;
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnFami;
    private javax.swing.JButton btnFlor;
    private javax.swing.JButton btnFrut;
    private javax.swing.JButton btnRegre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
