/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traductor;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMN
 */
public class FColor extends javax.swing.JFrame {

    /**
     * Creates new form FColor
     */
    public FColor() {
        initComponents();
        setLocationRelativeTo(null);
        llenarColor();
    }

    public void llenarColor() {
        tColor.setDefaultRenderer(Object.class, new ponerImagen());
        String tit[] = {"Spanish", "English", "Image"};
        DefaultTableModel tm = new DefaultTableModel(null, tit);
        ArrayList<Palabras> a = colores();
        for (Palabras aux : a) {

            //System.out.println(aux.getSapanish() + aux.getEnglish() + aux.getIma());
            JLabel fu = new JLabel();
            fu.setSize(245, 150);
            ImageIcon icon = new ImageIcon(getClass().getResource("Archivos/" + aux.getIma()));
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(fu.getWidth(), fu.getHeight(), Image.SCALE_DEFAULT));
            fu.setIcon(icono);
            tm.addRow(new Object[]{aux.getSapanish(), aux.getEnglish(), fu});

        }
        tColor.setRowHeight(150);
        tColor.setModel(tm);
        tColor.getColumnModel().getColumn(2).setPreferredWidth(185);
    }

    public ArrayList<Palabras> colores() {
        ArrayList<Palabras> col = new ArrayList();
        for (Palabras aux : Aprender.regist.traer_Palabra()) {
            if (aux.getTipo().compareTo("color") == 0) {
                col.add(aux);
            }
        }
        return col;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tColor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colors");
        setBackground(new java.awt.Color(255, 204, 204));

        btnCerrar.setBackground(new java.awt.Color(255, 153, 153));
        btnCerrar.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(153, 0, 153));
        btnCerrar.setText("Close");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("COLORS");

        tColor.setBackground(new java.awt.Color(255, 153, 255));
        tColor.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        tColor.setForeground(new java.awt.Color(153, 0, 153));
        tColor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tColorMouseClicked(evt);
            }
        });
        tColor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tColorKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tColor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addGap(249, 249, 249))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tColorMouseClicked
        // TODO add your handling code here:
        Login.Music.Stop();
        int fila = this.tColor.getSelectedRow();
        String mu = String.valueOf(this.tColor.getValueAt(fila, 1));
        //mu.toLowerCase();
        Login.Music.Play("Archivos/" + mu + ".mp3");
    }//GEN-LAST:event_tColorMouseClicked

    private void tColorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tColorKeyReleased
        // TODO add your handling code here:
        if (tColor.getSelectedRows().length > 0) {
            Login.Music.Stop();
            int fila = this.tColor.getSelectedRow();
            String mu = String.valueOf(this.tColor.getValueAt(fila, 1));
            //mu.toLowerCase();
            Login.Music.Play("Archivos/" + mu + ".mp3");
        }
    }//GEN-LAST:event_tColorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tColor;
    // End of variables declaration//GEN-END:variables
}
