/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traductor;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laloo
 */
public class FFruta extends javax.swing.JFrame {

    /**
     * Creates new form FFruta
     */
    public FFruta() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        llenarFruta();
    }

    public void llenarFruta() {
        tFruta.setDefaultRenderer(Object.class, new ponerImagen());
        String tit[] = {"Spanish", "English", "Image"};
        DefaultTableModel tm = new DefaultTableModel(null, tit);
        ArrayList<Palabras> a = fruta();
        for (Palabras aux : a) {

            //System.out.println(aux.getSapanish() + aux.getEnglish() + aux.getIma());
            JLabel fu = new JLabel();
            fu.setSize(255, 150);
            ImageIcon icon = new ImageIcon(getClass().getResource("Archivos/" + aux.getIma()));
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(fu.getWidth(), fu.getHeight(), Image.SCALE_DEFAULT));
            fu.setIcon(icono);
            tm.addRow(new Object[]{aux.getSapanish(), aux.getEnglish(), fu});

        }
        tFruta.setRowHeight(150);
        tFruta.setModel(tm);
        tFruta.getColumnModel().getColumn(2).setPreferredWidth(185);
    }

    public ArrayList<Palabras> fruta() {
        ArrayList<Palabras> fru = new ArrayList();
        for (Palabras aux : Aprender.regist.traer_Palabra()) {
            if (aux.getTipo().compareTo("fruta") == 0) {
                fru.add(aux);
            }
        }
        return fru;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tFruta = new javax.swing.JTable();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fruits");
        setBackground(new java.awt.Color(246, 179, 112));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("FRUITS");

        tFruta.setBackground(new java.awt.Color(252, 115, 42));
        tFruta.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        tFruta.setForeground(new java.awt.Color(102, 0, 0));
        tFruta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tFruta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tFrutaMouseClicked(evt);
            }
        });
        tFruta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFrutaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tFruta);

        btnCerrar.setBackground(new java.awt.Color(255, 102, 0));
        btnCerrar.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1)
                        .addGap(0, 241, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tFrutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tFrutaMouseClicked
        // TODO add your handling code here:
        Login.Music.Stop();
        int fila = this.tFruta.getSelectedRow();
        String mu = String.valueOf(this.tFruta.getValueAt(fila, 1));
        //mu.toLowerCase();
        Login.Music.Play("Archivos/" + mu + ".mp3");
    }//GEN-LAST:event_tFrutaMouseClicked

    private void tFrutaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFrutaKeyReleased
        // TODO add your handling code here:
        if (tFruta.getSelectedRows().length > 0) {
            Login.Music.Stop();
            int fila = this.tFruta.getSelectedRow();
            String mu = String.valueOf(this.tFruta.getValueAt(fila, 1));
            //mu.toLowerCase();
            Login.Music.Play("Archivos/" + mu + ".mp3");
        }
    }//GEN-LAST:event_tFrutaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FFruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FFruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FFruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FFruta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FFruta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tFruta;
    // End of variables declaration//GEN-END:variables
}
