/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traductor;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMN
 */
public class Info extends javax.swing.JFrame {

    /**
     * Creates new form Info
     */
    public Info() {
        initComponents();
        setSize(715, 460);
        setLocationRelativeTo(null);
        setResizable(false);
        cargarInfo();
    }

    public void cargarInfo(){
        try {
            ImageIcon icon = new ImageIcon(Login.ini + "\\Fotos\\" + Login.jugador.getFoto());
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lb.getWidth(), lb.getHeight(), Image.SCALE_DEFAULT));
            lb.setText(null);
            lb.setIcon(icono);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al abrir..." + ex);
        }
        tName.setText(Login.jugador.getNombre());
        tLast.setText(Login.jugador.getApellido());
        tAge.setText(Integer.toString(Login.jugador.getEdad()));
        tUser.setText(Login.jugador.getUsuario());
        tEmail.setText(Login.jugador.getCorreo());
        lNiv.setText("Level " + Integer.toString(Login.nivJug));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lb = new javax.swing.JLabel();
        tName = new javax.swing.JTextField();
        tLast = new javax.swing.JTextField();
        tAge = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        tUser = new javax.swing.JTextField();
        btnRet = new javax.swing.JButton();
        lNiv = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User Information");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USER INFORMATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 20, 220, 27);

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 100, 80, 21);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Last Name:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 170, 100, 21);

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 220, 35, 30);

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("User:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 280, 37, 30);

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E-mail Adress:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 350, 108, 21);

        lb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMouseClicked(evt);
            }
        });
        getContentPane().add(lb);
        lb.setBounds(540, 80, 130, 130);

        tName.setBackground(new java.awt.Color(0, 123, 95));
        tName.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tName.setForeground(new java.awt.Color(255, 255, 255));
        tName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tName);
        tName.setBounds(200, 100, 180, 30);

        tLast.setBackground(new java.awt.Color(0, 123, 95));
        tLast.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tLast.setForeground(new java.awt.Color(255, 255, 255));
        tLast.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tLast);
        tLast.setBounds(200, 160, 180, 30);

        tAge.setBackground(new java.awt.Color(0, 123, 95));
        tAge.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tAge.setForeground(new java.awt.Color(255, 255, 255));
        tAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tAge);
        tAge.setBounds(200, 220, 180, 30);

        tEmail.setBackground(new java.awt.Color(0, 123, 95));
        tEmail.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tEmail.setForeground(new java.awt.Color(255, 255, 255));
        tEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tEmail);
        tEmail.setBounds(200, 340, 320, 30);

        tUser.setBackground(new java.awt.Color(0, 123, 95));
        tUser.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        tUser.setForeground(new java.awt.Color(255, 255, 255));
        tUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tUser);
        tUser.setBounds(200, 280, 180, 30);

        btnRet.setBackground(new java.awt.Color(0, 102, 102));
        btnRet.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnRet.setForeground(new java.awt.Color(255, 255, 255));
        btnRet.setText("Return");
        btnRet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetActionPerformed(evt);
            }
        });
        getContentPane().add(btnRet);
        btnRet.setBounds(563, 390, 90, 31);

        lNiv.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lNiv.setForeground(new java.awt.Color(255, 255, 255));
        lNiv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lNiv);
        lNiv.setBounds(550, 240, 110, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traductor/in.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, -20, 710, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnRetActionPerformed

    private void lbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lNiv;
    private javax.swing.JLabel lb;
    private javax.swing.JTextField tAge;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tLast;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tUser;
    // End of variables declaration//GEN-END:variables
}
