/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traductor;

import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMN
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        cargar();
        Login.Music.Play("Archivos/pok.mp3");
    }

    public void abrir(String archivo) {
        try {
            File objetofile = new File(archivo);
            Desktop.getDesktop().open(objetofile);
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }

    public void cargar() {

        lUsuario.setText(Login.jugador.getUsuario());
        lNivel.setText("Level: " + Integer.toString(Login.nivJug));
        try {
            ImageIcon icon = new ImageIcon(Login.ini + "\\Fotos\\" + Login.jugador.getFoto());
            Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lIma.getWidth(), lIma.getHeight(), Image.SCALE_DEFAULT));
            lIma.setText(null);
            lIma.setIcon(icono);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al abrir..." + ex);
        }

        if (Login.jugador.getUsuario().compareTo("Lalouw") == 0
                || Login.jugador.getUsuario().compareTo("Pao") == 0
                || Login.jugador.getUsuario().compareTo("Alexis") == 0) {
            btnMarci.setVisible(true);
            btnPrint.setVerifyInputWhenFocusTarget(true);
        } else {
            btnMarci.setVisible(false);
            btnPrint.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNivel = new javax.swing.JLabel();
        lUsuario = new javax.swing.JLabel();
        btnAprender = new javax.swing.JButton();
        btnEjercicios = new javax.swing.JButton();
        lIma = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnMarci = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Learn English");
        setMinimumSize(new java.awt.Dimension(1365, 740));
        getContentPane().setLayout(null);

        lNivel.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        lNivel.setForeground(new java.awt.Color(0, 153, 255));
        lNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lNivel);
        lNivel.setBounds(1170, 220, 110, 30);

        lUsuario.setFont(new java.awt.Font("Berlin Sans FB", 0, 32)); // NOI18N
        lUsuario.setForeground(new java.awt.Color(0, 153, 255));
        lUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lUsuario);
        lUsuario.setBounds(1110, 180, 230, 40);

        btnAprender.setBackground(new java.awt.Color(51, 153, 255));
        btnAprender.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        btnAprender.setForeground(new java.awt.Color(255, 255, 255));
        btnAprender.setText("Learn");
        btnAprender.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnAprender.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAprender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprenderActionPerformed(evt);
            }
        });
        getContentPane().add(btnAprender);
        btnAprender.setBounds(120, 570, 230, 60);

        btnEjercicios.setBackground(new java.awt.Color(51, 153, 255));
        btnEjercicios.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        btnEjercicios.setForeground(new java.awt.Color(255, 255, 255));
        btnEjercicios.setText("Play");
        btnEjercicios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        btnEjercicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEjercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjerciciosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEjercicios);
        btnEjercicios.setBounds(480, 570, 230, 60);

        lIma.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lIma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lIma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lImaMouseClicked(evt);
            }
        });
        getContentPane().add(lIma);
        lIma.setBounds(1160, 50, 130, 130);

        btnSalir.setBackground(new java.awt.Color(51, 102, 255));
        btnSalir.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Log Out");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(1160, 260, 130, 37);

        btnMarci.setBackground(new java.awt.Color(204, 204, 255));
        btnMarci.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnMarci.setForeground(new java.awt.Color(255, 255, 255));
        btnMarci.setText("Show Marcianito");
        btnMarci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarciActionPerformed(evt);
            }
        });
        getContentPane().add(btnMarci);
        btnMarci.setBounds(50, 40, 170, 40);

        btnPrint.setBackground(new java.awt.Color(249, 227, 89));
        btnPrint.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(0, 0, 0));
        btnPrint.setText("Print Users");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint);
        btnPrint.setBounds(1130, 630, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/traductor/LearnEnglish.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -20, 1370, 810);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjerciciosActionPerformed
        // TODO add your handling code here:
        Ejercicios abrir = new Ejercicios();
        abrir.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btnEjerciciosActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "Do you want to go out?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            Login.registros.modificarNivel(Login.jugador.getUsuario(), Login.nivJug);
            Login.Music.Stop();
            Login abrir = new Login();
            abrir.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAprenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprenderActionPerformed
        // TODO add your handling code here:
        Aprender abrir = new Aprender();
        abrir.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btnAprenderActionPerformed

    private void lImaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lImaMouseClicked
        // TODO add your handling code here:
//        JOptionPane.showMessageDialog(null, "Si sirvo");
        Info in = new Info();
        in.setVisible(true);
    }//GEN-LAST:event_lImaMouseClicked

    private void btnMarciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarciActionPerformed
        // TODO add your handling code here:
        Marcianito ab = new Marcianito();
        ab.setVisible(true);
        Login.Music.Stop();
        Login.Music.Play("Archivos/mar.mp3");
    }//GEN-LAST:event_btnMarciActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        ArrayList<IPersona> u = Login.registros.consultarUsuario();
        String us = "";
        int uu = 1;
        for (IPersona aux : u) {
            us = us + "User No." + Integer.toString(uu)
                    + "\nName: " + aux.getNombre()
                    + "\nLast Name: " + aux.getApellido()
                    + "\nAge: " + Integer.toString(aux.getEdad())
                    + "\nUser: " + aux.getUsuario()
                    + "\nPassword: " + aux.getPassword()
                    + "\nE-mail: " + aux.getCorreo()
                    + "\nLevel: " + Integer.toString(aux.getNivel())
                    + "\nImage: " + aux.getFoto() + "\n\n";
            uu++;
        }
        Codigo yuki = new Codigo(us);
        yuki.mandarPdf();
        
        int op = JOptionPane.showConfirmDialog(null, "Do you want to open the file?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {
            abrir("Users.pdf");
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprender;
    private javax.swing.JButton btnEjercicios;
    private javax.swing.JButton btnMarci;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lIma;
    public static javax.swing.JLabel lNivel;
    private javax.swing.JLabel lUsuario;
    // End of variables declaration//GEN-END:variables
}
